version: "3"

services:
  openproject-discord-webhook-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./requests/:/app/requests/
      - ./config.yaml:/app/config.yaml
  minio:
    image: quay.io/minio/minio
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9001:9000"
      - "9002:9001"

volumes:
  minio:
